### ISSUE TITLE
workers do not work with memcache

### ISSUE THREAD

**Issue by sfai05** [wa0x6e/php-resque-ex#19]
I am running in wordpress env. with memcache
However only the first task in worker can read/write into memcache
start from the second task memcache always return empty.

Any suggestion?

**Comment by duyquang1202** [comment]
@sfai05 : You solved it. I'm facing with same problem. Please help me.
Thank you so much.

**Comment by sfai05** [comment]
@duyquang1202 @wa0x6e was right. The memcached connection die after the first task in the worker is finished. You need to re-connect to memcache server in `setUp`

e.g.
```
	public function setUp() {
		//reconnect memcache
		global $wp_object_cache, $memcached_servers;
		$m2 = new Memcached();
		if ( isset( $memcached_servers ) )
			$servers = $memcached_servers;
		else
			$servers = array( array( '127.0.0.1', 11211 ) );
		$m2->addServers( $servers );

		$wp_object_cache->m = $m2;
	}
```
