### ISSUE TITLE
Resque_Failure_Redis implementation incompatible with Ruby resque

### ISSUE THREAD

**Issue by mfn** [wa0x6e/php-resque-ex#26]
The implementation of `Resque_Failure_Redis` looks currently like this:

``` php
Resque::Redis()->setex('failed:'.$payload['id'], 3600*14, serialize($data));
```

The [php-resque implementation is different](https://github.com/chrisboulton/php-resque/blob/c335bc35558e0683f95c3fd5dd11a5817c0a761f/lib/Resque/Failure/Redis.php#L31):

``` php
Resque::redis()->rpush('failed', $data);
```

which is more in-line how the Ruby resque implementation expects to displayed the statistics of failed jobs: [it counts the elements in the `failed` key](https://github.com/resque/resque/blob/63ed8b95c39c9c12dbc0dd68da02c2c638b31f1b/lib/resque.rb#L463)

I don't find any information stating that `php-resque-ex` deliberately breaks compatibility with resque thus I assume it's a bug, although it's obvious it's not by accident as it's clearly a different take on the implementation:

> You can easily retrieve logs for a failed jobs in the redis database, their keys are named after their job ID. Each failed log will expire after 2 weeks to save space.

---

Btw, the current implementation seems to have a TTL of 14 hours, not 14 days:

``` php
Resque::Redis()->setex('failed:'.$payload['id'], 3600*14, serialize($data));
```

According to the [redis SETEX it seconds](http://redis.io/commands/SETEX)

**Comment by johannesnagl** [comment]
any updates on this one?

**Comment by mfn** [comment]
Not using resque anymore -> closing
