### ISSUE TITLE
 Could not find job class Queue\emailQueue.

### ISSUE THREAD

**Issue by msaraac** [wa0x6e/php-resque-ex#49]
Processing ID:bd853192891aa109c6e2b9a4b8e83ab3 in default
[2017-11-02T23:24:23+00:00] {"queue":"default","id":"bd853192891aa109c6e2b9a4b8e83ab3","class":"Queue\\emailQueue","args":[{"ali":"deli"}]} failed: Could not find job class Queue\emailQueue.

So my verbose log is like this. I couldnt manage to handle classes to run.In my case classes cannot load.I used composer to install this lib. Thanks

```
(class_exists('Queue/emailQueue')
returns true what should I do
```
@ @jmathai @hobodave @KevBurnsJr @maetl @mfauveau

**Comment by msaraac** [comment]
anyone ? I really need this help

**Comment by jision** [comment]
Hey the problem is the resque is not getting the path of the worker class use a full path and see.

**Comment by KevBurnsJr** [comment]
^ ```\Queue\emailQueue```

**Comment by wa0x6e** [comment]
Try using APP_INCLUDE

https://github.com/wa0x6e/php-resque-ex#job-creation-delegation
